# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d533861434c9ca888151e6b4db123c5df6d1e1431b2c9752572dd148e54508e3ddea09fb2df7a47b884833e40c48cbf5593421c19304582f2f1b52094e6a226

test:
  secret_key_base: 847596dc0b42ef00a2a34d75ee31f828d9a9edc0233e64889b8bd73909d2ba360585f025b8f508dc8ebdd8646fc57a47726a790f7de09e24af752e9048db8642

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
